pushes first then asks to force push

diff --git a/bin/git-rebase-develop-into-feature-branches b/bin/git-rebase-develop-into-feature-branches
--- a/bin/git-rebase-develop-into-feature-branches
+++ b/bin/git-rebase-develop-into-feature-branches
@@ -42,8 +42,20 @@ for _feature_branch in `git-flow-feature-branches`; do
       echo
       echo "Rebase successful."
       echo
-      if ( _prompt_warning "Do you want to force push this branch '$_feature_branch' to your default remote? WARNING: This a potentially destructive action.") ; then
-        git push --force
+      if ( _prompt_success "Do you want to push this branch '$_feature_branch' to your default remote?") ; then
+
+        git push
+
+        if [[ $? != 0 ]] ; then
+
+          echo
+          echo "Push failed. You probably need to force push."
+          echo
+
+          if ( _prompt_warning "Do you want to force push this branch '$_feature_branch' to your default remote? WARNING: This a potentially destructive action.") ; then
+            git push --force
+          fi
+        fi
       fi
     fi
 
